# Generated by Django 3.0.4 on 2020-04-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='title',
            field=models.CharField(default='', max_length=120),
        ),
    ]
