# Generated by Django 3.0.4 on 2020-04-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_headline_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='coronavirusCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.TextField()),
            ],
        ),
    ]
