# Generated by Django 3.0.4 on 2020-04-03 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_coronaviruscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coronaviruscount',
            old_name='count',
            new_name='virusCount',
        ),
    ]
