# Generated by Django 3.0.4 on 2020-04-04 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200403_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
