# Generated by Django 3.0.6 on 2020-05-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200403_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='description',
            field=models.CharField(default='', max_length=240),
        ),
    ]
